-- Haseki Patoloji Eğitim Programı - Tablo Oluştur
CREATE TABLE IF NOT EXISTS schedule_events (
  id        BIGSERIAL PRIMARY KEY,
  date      TEXT NOT NULL,
  date_string TEXT,
  time      TEXT NOT NULL,
  category  TEXT DEFAULT 'lab',
  image_url TEXT,
  speakers  JSONB DEFAULT '[]',
  topics    JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Herkes okuyabilsin (anon read)
ALTER TABLE schedule_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Herkes okuyabilir" ON schedule_events
  FOR SELECT USING (true);

CREATE POLICY "Herkes yazabilir" ON schedule_events
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Herkes guncelleyebilir" ON schedule_events
  FOR UPDATE USING (true);

CREATE POLICY "Herkes silebilir" ON schedule_events
  FOR DELETE USING (true);

-- Frozen Listesi Tablosu
CREATE TABLE IF NOT EXISTS frozen_events (
  id        BIGSERIAL PRIMARY KEY,
  date      DATE NOT NULL UNIQUE,
  specialist TEXT NOT NULL,
  assistant  TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE frozen_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes okuyabilir_frozen" ON frozen_events FOR SELECT USING (true);
CREATE POLICY "Herkes yazabilir_frozen" ON frozen_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Herkes guncelleyebilir_frozen" ON frozen_events FOR UPDATE USING (true);
CREATE POLICY "Herkes silebilir_frozen" ON frozen_events FOR DELETE USING (true);

-- Mesajlar Tablosu
CREATE TABLE IF NOT EXISTS user_messages (
  id        BIGSERIAL PRIMARY KEY,
  content   TEXT NOT NULL,
  sender_info TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes yazabilir_msg" ON user_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Sadece admin okuyabilir_msg" ON user_messages FOR SELECT USING (true);
CREATE POLICY "Herkes silebilir_msg" ON user_messages FOR DELETE USING (true);

-- Bildirim Abonelikleri Tablosu
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT DEFAULT 'admin',
    subscription_data JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id)
);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes ekleyebilir_push" ON push_subscriptions FOR INSERT WITH CHECK (true);
CREATE POLICY "Herkes okuyabilir_push" ON push_subscriptions FOR SELECT USING (true);
CREATE POLICY "Herkes güncelleyebilir_push" ON push_subscriptions FOR UPDATE USING (true);
